name: PythonTutorial
channels:
  - anaconda
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - anyio=4.8.0
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=3.0.0
  - async-lru=2.0.4
  - attrs=25.1.0
  - babel=2.17.0
  - beautifulsoup4=4.13.3
  - blas=1.0
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.7.14
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2025.7.14
  - cffi=1.17.1
  - charset-normalizer=3.4.1
  - comm=0.2.2
  - contourpy=1.3.1
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - dbus=1.13.18
  - debugpy=1.8.12
  - decorator=5.1.1
  - defusedxml=0.7.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.6.4
  - fontconfig=2.14.1
  - fonttools=4.55.3
  - fqdn=1.5.1
  - freetype=2.12.1
  - glib=2.78.4
  - glib-tools=2.78.4
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - h11=0.14.0
  - h2=4.2.0
  - hpack=4.1.0
  - httpcore=1.0.7
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=73.1
  - idna=3.10
  - importlib-metadata=8.6.1
  - importlib_resources=6.5.2
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=8.32.0
  - ipywidgets=8.1.7
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.5
  - joblib=1.4.2
  - jpeg=9e
  - json5=0.10.0
  - jsonpointer=3.0.0
  - jsonschema=4.23.0
  - jsonschema-specifications=2024.10.1
  - jsonschema-with-format-nongpl=4.23.0
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.12.0
  - jupyter_server=2.15.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.3.5
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.15
  - kiwisolver=1.4.8
  - krb5=1.20.1
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20240116.2
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcups=2.4.2
  - libcurl=8.12.0
  - libdeflate=1.22
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.78.4
  - libgomp=14.2.0
  - libiconv=1.16
  - libllvm14=14.0.6
  - libmpdec=4.0.0
  - libnghttp2=1.57.0
  - libpng=1.6.39
  - libpq=17.2
  - libprotobuf=4.25.3
  - libsodium=1.0.18
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.5.1
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.13.5
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - matplotlib-inline=0.1.7
  - mistune=3.1.1
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mysql=8.4.0
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - notebook-shim=0.2.4
  - numexpr=2.10.1
  - numpy=2.2.2
  - numpy-base=2.2.2
  - openjpeg=2.5.2
  - openldap=2.6.4
  - openssl=3.5.1
  - overrides=7.7.0
  - packaging=24.2
  - pandas=2.2.3
  - pandocfilters=1.5.0
  - parso=0.8.4
  - patsy=1.0.1
  - pcre2=10.42
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.1.0
  - pip=24.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.6
  - ply=3.11
  - prometheus_client=0.21.1
  - prompt-toolkit=3.0.50
  - psutil=6.1.1
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.19.1
  - pyparsing=3.2.0
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - python=3.13.2
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.21.1
  - python-json-logger=2.0.7
  - python-tzdata=2023.3
  - python_abi=3.13
  - pytz=2025.1
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - qt-main=5.15.2
  - readline=8.2
  - referencing=0.36.2
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.22.3
  - scikit-learn=1.6.1
  - scipy=1.15.1
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - send2trash=1.8.3
  - setuptools=72.1.0
  - sip=6.7.12
  - six=1.16.0
  - sniffio=1.3.1
  - soupsieve=2.5
  - sqlite=3.45.3
  - stack_data=0.6.3
  - statsmodels=0.14.4
  - tbb=2021.8.0
  - terminado=0.18.1
  - threadpoolctl=3.5.0
  - tinycss2=1.4.0
  - tk=8.6.14
  - tomli=2.2.1
  - tornado=6.4.2
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20241206
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - typing_utils=0.1.0
  - tzdata=2025a
  - uri-template=1.3.0
  - urllib3=2.3.0
  - wcwidth=0.2.13
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.44.0
  - widgetsnbextension=4.0.14
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - build==1.2.2.post1
      - et-xmlfile==2.0.0
      - iniconfig==2.0.0
      - narwhals==1.46.0
      - openpyxl==3.1.5
      - pip-chill==1.0.3
      - plotly==6.2.0
      - pluggy==1.5.0
      - pyproject-hooks==1.2.0
      - pytest==8.3.4
