"""Use the extension module built by make_cffi.py."""

import numpy as np
from _mathlib_cffi import ffi, lib  # generated by make_cffi.py


class Accumulator:
    def __init__(self, start: float = 0.0, name: str = "acc") -> None:
        handle = lib.ml_acc_create(start, name.encode())
        if handle == ffi.NULL:
            raise MemoryError("ml_acc_create failed")
        # ffi.gc attaches the destructor to the Python object's lifetime, so the
        # C++ object is freed when the wrapper is collected. Nicer than ctypes,
        # where you write __del__ yourself.
        self._h = ffi.gc(handle, lib.ml_acc_destroy)

    def add(self, v: float) -> None:
        lib.ml_acc_add(self._h, v)

    @property
    def total(self) -> float:
        return lib.ml_acc_total(self._h)

    @property
    def name(self) -> str:
        return ffi.string(lib.ml_acc_name(self._h)).decode()

    def history(self) -> np.ndarray:
        n = lib.ml_acc_size(self._h)
        out = np.empty(n, dtype=np.float64)
        # ffi.cast on the NumPy data pointer = zero copy.
        written = lib.ml_acc_history(self._h, ffi.cast("double *", out.ctypes.data), n)
        return out[:written]


def divide(a: float, b: float) -> float:
    out = ffi.new("double *")
    if lib.ml_divide(a, b, out) != 0:
        raise ZeroDivisionError(f"{a} / {b}")
    return out[0]


def main() -> None:
    print("add(2, 3)          =", lib.ml_add(2.0, 3.0))

    arr = np.arange(5, dtype=np.float64)
    lib.ml_scale_inplace(ffi.cast("double *", arr.ctypes.data), arr.size, 10.0)
    print("scale_inplace(x10) =", arr)

    print("divide(1, 4)       =", divide(1.0, 4.0))
    try:
        divide(1.0, 0.0)
    except ZeroDivisionError as exc:
        print("divide(1, 0)       -> ZeroDivisionError:", exc)

    acc = Accumulator(1.0, "cffi-acc")
    for v in (2.0, 3.0, 4.0):
        acc.add(v)
    print(f"{acc.name}: total={acc.total} history={acc.history()}")


if __name__ == "__main__":
    main()
